version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: xdebug
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
      - /work/backend/vendor
    environment:
      - XDEBUG_LOAD_MODULE=${XDEBUG_LOAD_MODULE}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_START_WITH_REQUEST=${XDEBUG_START_WITH_REQUEST}
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT}
      - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}

  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
    depends_on:
      - app
      - db

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-store:
  php-fpm-socket:
