name: phalcon-create-project

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Version
        run: docker-compose --version
      - name: Build Docker
        run: |
          cd infrastructure
          docker-compose build
          docker-compose up -d web
          docker-compose ps
      - name: Create Phalcon Project
        run: |
          cd infrastructure
          docker-compose exec -T app php --version
          docker-compose exec -T app composer --version
          docker-compose exec -T app composer require --dev phalcon/devtools
          docker-compose exec -T app vendor/bin/phalcon project template --directory=/tmp --enable-webtools
          docker-compose exec -T app sh -c 'cp -afb /tmp/template/* ./'
      - name: PHP and phalcon Version
        run: |
          cd infrastructure
          docker-compose exec -T app ./vendor/bin/phalcon info
#      - name: Laravel Migrate, Rollback, Seeding Testing
#        run: |
#          cd infrastructure
#          docker-compose exec -T app php artisan migrate
#          docker-compose exec -T app php artisan migrate:refresh --seed
#      - name: Laravel Testing
#        run: |
#          cd infrastructure
#          docker-compose exec -T app php artisan test
