name: phalcon-create-project

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Version
        run: docker-compose --version
      - name: Create Phalcon Project
        run: |
          cd infrastructure
          make create-project
          make ps
      - name: Recommend packages install
        run: |
          cd infrastructure
          make install-recommend-packages
      - name: PHP and phalcon Version
        run: |
          cd infrastructure
          make info
#      - name: Laravel Migrate, Rollback, Seeding Testing
#        run: |
#          cd infrastructure
#          docker-compose exec -T app php artisan migrate
#          docker-compose exec -T app php artisan migrate:refresh --seed
#      - name: Laravel Testing
#        run: |
#          cd infrastructure
#          docker-compose exec -T app php artisan test
